[package]
name = "Idle_Threshold_Changer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "*"
egui = "*"
egui_extras = { version = "*", features = ["all_loaders"] }
image = { version = "*", features = ["png"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
rfd = "*"
rodio = { version = "0.20", features = ["wav"] }
webbrowser = "1.0"
winres = "*"

# Pindahkan winres ke sini Bang
[build-dependencies]
winres = "*"
